/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mia;

import mia.core.Mia;

public class App {
    public static void main(String[] args) {
        new Mia();
    }
}
